services:
  whisperx:
    image: ghcr.io/jim60105/whisperx:large-v3-ja
    working_dir: /app
    volumes:
      - ${INPUT_VIDEOS_DIR:-./src_video}:/app
      - ${OUTPUT_DIR:-./output}:/output
      - ./cache:/.cache
    command: []
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
